# Generated by Django 6.0.5 on 2026-09-22 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_experience_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
